### ISSUE TITLE
Investigar sobre las Ceremonias

### ISSUE THREAD

**Issue by ProgramadorPegasus** [ProgramadorPegasus/A1-SCRUM-TSDWAD-2022#5]

**Comment by CintiaOsorioDuartesakura** [comment]
**Ceremonias que se realizan a lo largo del proyecto:**

_**Sprint Planning Meeting**_ (reunión de planificación del sprint). Se produce al iniciar cada
Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.

_**Daily Scrum Meeting**_ (reunión periódica). Se produce diariamente, y tiene un máximo de
20 min. de duración. Tiene por objeto tratar qué es lo que se hizo , qué se va a hacer y
qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.

_**Sprint Review Meeting**_ (reunión de revisión del Sprint). Se produce al finalizar el Sprint y
tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el
Product Owner.

_**Sprint Retrospective Meeting**_ (reunión de retrospectiva del Sprint). Se produce también al
finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado
en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que
debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.
