### ISSUE TITLE
Investigar sobre Artefactos

### ISSUE THREAD

**Issue by ProgramadorPegasus** [ProgramadorPegasus/A1-SCRUM-TSDWAD-2022#6]

**Comment by Yamiibel** [comment]
En el marco de trabajo Scrum, denominamos Artefacto a aquellos elementos físicos que se producen como resultado de la aplicación de Scrum. Los tres principales artefactos o herramientas Scrum son:

1) Product Backlog: es la principal fuente de información, refleja el estado real del trabajo pendiente de implementar en el producto, así como el ya realizado. 
Debe ser gestionado en exclusiva por el Product Owner, siendo su principal función la de priorizar aquellos elementos que tienen más valor en cada etapa y detallarlos para que el equipo de desarrollo sea capaz de valorarlos y ejecutarlos.
Un Product Backlog contiene distintos elementos:
*Funcionalidades
*Bugs
*Historias de usuario: una forma de expresar elementos de un Product Backlog. Para obtener el máximo valor de una historia de usuarios es necesario expresarlas desde el punto de vista del usuario.
*Tareas técnicas.
*Trabajo de investigación.

2) Sprint Backlog: permite visualizar, durante cada Sprint, aquellos elementos que aún no han empezado a desarrollarse, aquellos que sí y quiénes están trabajando en los mismos, así como aquellos que están esperando a desplegarse o están completamente terminados. Este artefacto permite entender cuál es la evolución del trabajo, así como hacer un análisis de riesgos. Dado que cada Sprint tiene una meta específica y hay elementos seleccionados del Product Backlog que tienen más o menos valor, el Sprint Backlog permite analizar hasta donde se ha cumplido el objetivo y que se podría eliminar. De esta forma, maximizamos el retorno de la inversión en desarrollo.

3) Incremento: es el resultado del Sprint, es la suma de todas las tareas, casos de uso, historias de usuario y cualquier elemento que se haya desarrollado durante el Sprint y que será puesto a disposición del usuario final en forma de software, aportando un valor de negocio al producto que se está desarrollando.
